### PR TITLE
Add SC selector

### PR DESCRIPTION
**Pull request by kingy04**
Adds a supercroud / user selector to the styleguide

### CODE REVIEW

**Comment by kingy04** [comment]
I have used global styles rather than scoped with the deep selector unless you have any idea for that fellas, snapshot test incoming.

Cheers

**Comment by BrockReece** [comment]
Is the `>>>` combinator not working?

**Comment by BrockReece** [comment]
I think the version of vue-loader needs updating in the style guide, I will look into it. The >>> combinator is only supported since v12.0.2.

**Comment by kingy04** [comment]
Lets see where i get too mate, will let you know.. thanks for the offer

**Comment by BrockReece** [comment]
Jut ran the styleguide and saw that the tooltip isn't working properly.
screen shot 2017-11-09 at 17 32 53

**Comment by kingy04** [comment]
Updated vue loader for the scoped styles fix, also updated vue-croud-semantic and applied changes to the import statements for vue loader. I fixed the summary tooltip also.

**Comment by kingy04** [comment]
This still needs a quick snapshot test but it might have to wait until i'm back now..

Cheers

**Comment by BrockReece** [comment]
There are a few little things to tidy up, I will add a snapshot test while I am at it.

**Pull request merged**
